### ISSUE TITLE
Question: Is this a replacement or extension?

### ISSUE THREAD

**Issue by bt-88** [wilchn/BlazingQuartz#39]
Hi there,

From reading the docs it's not entirely clear what this is. It seems that this also includes a scheduler or 'worker', as well as the dashboard itself.

In my use case I would like to run the dashboard separately, and hook it up to my my scheduler backend (sql server).

Is that possible?

**Comment by wilchn** [comment]
The intent is to make it as extension of your existing Quartz scheduler. [BlazingQuartzApp](https://github.com/wilchn/BlazingQuartz/tree/dev/src/BlazingQuartz/BlazingQuartzApp) is an example of how to use it.
